spring:
  application:
  name: General-Utility-Demo
  datasource:
    url: jdbc:mysql://localhost:3306/mychatgpt
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      url: redis://123.57.181.19:30379

  # application.yml 中配置 Hibernate 自动创建表
  jpa:
    hibernate:
      ddl-auto: update

  rhino-boot-turbo:
    global-enable: true


logging:
  file:
    path: /var/log
  level:
    org:
      springframework:
        security: DEBUG
      jooq: DEBUG

persist:
  dataMasking: true
  cryptography: true
  likeQuery: true

security:
  ignore:
    urls:
      - /user/**
      - /save
      - /export
